"""initial schema

Revision ID: 7311cabb48d9
Revises:
Create Date: 2026-08-08 19:23:22.324629

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7311cabb48d9"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # `budgets.user_id` and `users.active_budget_id` reference each other, so
    # the cross-FK is added separately below once both tables exist.
    op.create_table(
        "budgets",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("note", sa.String(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("display_name", sa.String(), nullable=False),
        sa.Column("active_budget_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(["active_budget_id"], ["budgets.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_foreign_key(
        "fk_budgets_user_id_users", "budgets", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.create_table(
        "categories",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "system_type",
            sa.Enum("income", "saving_goal", "debt", name="category_system_type"),
            nullable=True,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "expenses",
        sa.Column("budget_id", sa.UUID(), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=False),
        sa.Column(
            "series_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("note", sa.String(), nullable=True),
        sa.Column("cost", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "frequency",
            sa.Enum(
                "daily", "weekly", "monthly", "yearly", "custom", "once", name="expense_frequency"
            ),
            nullable=False,
        ),
        sa.Column(
            "monthly_cost",
            sa.Numeric(precision=12, scale=2),
            sa.Computed(
                "\nCASE frequency\n    WHEN 'daily' THEN cost * 30\n    WHEN 'weekly' THEN cost * 52.0 / 12\n    WHEN 'monthly' THEN cost\n    WHEN 'yearly' THEN cost / 12\n    WHEN 'once' THEN cost\n    WHEN 'custom' THEN cost / GREATEST(\n        (EXTRACT(YEAR FROM goal_date) - EXTRACT(YEAR FROM period)) * 12\n        + (EXTRACT(MONTH FROM goal_date) - EXTRACT(MONTH FROM period)),\n        1\n    )\nEND\n",  # noqa: E501
                persisted=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "amount_saved", sa.Numeric(precision=12, scale=2), server_default="0", nullable=False
        ),
        sa.Column("goal_amount", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("goal_date", sa.Date(), nullable=True),
        sa.Column("period", sa.Date(), nullable=False),
        sa.Column("is_deactivated", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(["budget_id"], ["budgets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "budget_id", "period", "series_id", name="uq_expense_budget_period_series"
        ),
    )
    op.create_table(
        "transactions",
        sa.Column("expense_id", sa.UUID(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("spend", "spend_saved", "save", "transfer", "income", name="transaction_type"),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("note", sa.String(), nullable=True),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("transfer_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(["expense_id"], ["expenses.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["transfer_id"], ["transactions.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transactions")
    op.drop_table("expenses")
    op.drop_table("categories")
    op.drop_constraint("fk_budgets_user_id_users", "budgets", type_="foreignkey")
    op.drop_table("users")
    op.drop_table("budgets")
    # ### end Alembic commands ###
