"""add note to savings

Revision ID: d48796019c83
Revises: e4b2d9c61a07
Create Date: 2026-10-01 19:05:27.415304

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d48796019c83"
down_revision: str | Sequence[str] | None = "e4b2d9c61a07"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("savings", sa.Column("note", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("savings", "note")
    # ### end Alembic commands ###
